### ISSUE TITLE
ParseTokensToCommand fails on zero length list

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutate4l#3]
![image](https://user-images.githubusercontent.com/915232/56835337-d3759a80-686b-11e9-8c4d-db507d9b44a1.png)

Getting a System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Arg_ParamName_Name' sometimes. I am guessing this is linked to the initial setup with the backend but I'm not 100% sure on a repro case yet.

**Comment by twobob** [comment]
Okay, Looks like this might be when the new clip is added into a midi-only track, i.e one that does not terminate directly in an instrument. Adding an instrument certainly seems to fix it.  Part of the Robustify drive perhaps....

**Comment by twobob** [comment]
Repro. Add a midi only track and try and populate it by reference.
![image](https://user-images.githubusercontent.com/915232/56848502-ecb92e00-68e1-11e9-9bea-24b9ba360526.png)
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Arg_ParamName_Name'

**Comment by twobob** [comment]
hmm or perhaps it is just the single cell reference "=a1" expectation being a simple concat from the donor cell to the calculated cell? is that not the case?

**Comment by carrierdown** [comment]
Ah, yeah the formula =a1 would trigger that I guess, because it expects a command to be present. Will fix shortly :)

**Comment by twobob** [comment]
excellent, an implicit concat would be ideal, since that is the spreadsheet outcome, and the docs indicate spreadsheet like operation :)
