### ISSUE TITLE
Formulas that reference themselves causes calculation to recurse

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutate4l#4]
![image](https://user-images.githubusercontent.com/915232/56869799-49f5d200-69fd-11e9-9ccc-27ce6a5231dd.png)

constraining a part by another part by referencing itself causes the calc to be looped endlessly.

Probably don't want that.
so  
[A1] = a1 constrain -by b1
will cause a loop that occurs between the sender and receiver - hope it helps.

**Comment by carrierdown** [comment]
Yep, I know about this one. I imagine there are several such scenarios that can cause endless loops atm. Will have to do something about this eventually, but it's not at the top of my list currently.
