### ISSUE TITLE
REQUEST FOR INFORMATION. Durations greater than a quaver 

### ISSUE THREAD

**Issue by twobob** [carrierdown/mutate4l#9]
How does one express a crotchet, minim, semibreve and moreover multiples of those for durations?

I tried the obvious "1" for a crochet and got an error about mixing formats.
Rather than report that (annoyingly) as a bug I am checking how would one would express it.

I am assuming it must be 1/1 for crotchet, 2/1 minim, 4/1 semibreve, 8/1 breve, 16/1 longa, et cetera.

Lets say Take is the command. How would one say   
Start at  "4 bars and 2 beats" and take "2 bars and 3 beats"

is it 9/2 5/2 ?

If so, that's pretty tortuous for the average user probably, I am not even sure the maths in that example would be correct and obviously some really fiddly values could result. :\  And that was a really easy example :\\

perhaps some sort of shorthand?  Maybe check for two periods in the string and do a Bars.Beats.Ticks conversion? Live works like that internally AFAIK, at least as far as the average user is concerned.
Possibly request for enhancement?

**Comment by twobob** [comment]
is it 9/2 5/2  ?
That's pretty tortuous if so... perhaps some sort of shorthand?

**Comment by twobob** [comment]
hmm so durations with a denominator over 9 don't work.

> Received 2 clips and formula: [0] shuf -by [1] take 2/1 10/1
> Error: Unrecognized input at position 28:\r\n shuf -by [1] take 2/1 10/\r\n                         ^

That might be a bug

**Comment by carrierdown** [comment]
Yep, the idea is that you should be able to specify bars, but this isn’t implemented properly yet. It’s parsed as a number where it expects a decimal value. Will have to tweak the parser a bit to allow for this to work like it should:)

-Knut

**Comment by carrierdown** [comment]
Implementing a bars.beats.ticks type of format is also a possibility. Will get back to you on this when I have time to spare.

-Knut

**Comment by twobob** [comment]
I'm just struggling with the concept of a decimal. Because I can't pass 12.75 or something directly

**Comment by carrierdown** [comment]
Specifying that directly should also be possible, so several fixes are needed here. I think I agree with you on all counts, though :)

-Knut

**Comment by twobob** [comment]
Ah good to know. thanks. I will note any tiny things like silent fails on the Take command to a separate issues and try to look at them as time allows, like yourself.

**Comment by twobob** [comment]
Okay I see the issue in the parser with > 1 digit numerator values is simply an indexOf issue.   fair enough the b.b.t format thing seem doable, I shall look at it at some point then.

**Comment by twobob** [comment]
In terms of "discovering the token" properly

```
private bool IsMusicalDivision(int pos)
        {
            int nextSpace = pos;
            string TestTheString = string.Empty;
            while (!(nextSpace == Buffer.Length))
            {
                if (Char.IsWhiteSpace(Buffer[nextSpace]))
                { break; }
                TestTheString += Buffer[nextSpace];
                nextSpace++;
            }
            string pattern = @"\b[0-9]*\/[0-9]*\b";
            Match m = Regex.Match(TestTheString, pattern, RegexOptions.IgnoreCase);
        return m.Success;
}
```
(or a less pointlessly expansive version)  would do the job for detection. 
I'll dig around and see if I can sure up the extant MusicalDivision detection before adding anything new like B B T.

**Comment by carrierdown** [comment]
I'm actually working on doing MusicalDivisions properly now, along with a B.B.T format. Will report back :)

**Comment by carrierdown** [comment]
Thanks for looking into this. I'm probably going to refactor this section a bit though, and there's also some related parsing-logic which needs to be looked into. Might be I need to add some simple casting mechanics to get the various number formats working properly. It should for instance be possible to specify 12 as a musical value, which would be taken to mean 12 bars.

**Comment by twobob** [comment]
well. what I have now supports 
Received 1 clips and formula: [0] rl 1001/975 rl 1/2
Which will do for now until there is something else. 
Many thanks for your time

**Comment by carrierdown** [comment]
Great!

**Comment by carrierdown** [comment]
![parsertest](https://user-images.githubusercontent.com/1469068/56990214-ccfd6080-6b94-11e9-8b20-bcddd9605fcf.png)
Tests are looking good. Don't have time to test today, but have hopefully implemented implicit casting from i.e. number to musicaldivision. Also, parsing of musicaldivisions are now handled properly. Feel free to test if you have time to spare - it's on the branch feature/implicit-cast.

**Comment by twobob** [comment]
Thanks very much I'll grab it down and have a butchers

**Comment by carrierdown** [comment]
Just added support for input in the format beats.bars.sixteents (as used in Live) and tightened up casting logic. Not merged to master yet, so feature/implicit-cast is the place to be ;)

**Comment by carrierdown** [comment]
Now merged to master. Closing this issue :)
